implemented login ability for user
iodream/Spend-Note pull request #13
Opened 2022-01-16 12:12 UTC by MaksymTerekhovskyy

- added sha1 password encryption 
- implemented response status check

2022-01-16 16:09 UTC, AndriyFedorenko commented on src/Client/Controller/Controller.cpp
> +    if(response.status >= 400)
Please don't use magic number you can define constant or use Poco statuses.
https://docs.pocoproject.org/current/Poco.Net.HTTPResponse.html

2022-01-16 16:09 UTC, AndriyFedorenko commented on src/Client/Models/LoginModel.cpp
> +    json.insert("password", QString(encrypted_password));
Something wrong with code formatting.

2022-01-16 16:09 UTC, AndriyFedorenko commented on src/Client/View/LoginPage/LoginPage.cpp
> +	loginInDTO.login	= ui->loginLineEdit->text().toStdString();
Something wrong with code formatting. Why some many spaces between login and =

2022-01-16 16:09 UTC, AndriyFedorenko commented on src/Client/View/MainWindow.h
> +	static int PageToInt(UIPages page);
Something wrong with code formatting.

2022-01-16 18:21 UTC, MaksymTerekhovskyy commented on src/Client/Controller/Controller.cpp
> +    if(response.status >= 400)
fixed in the last commit

2022-01-16 18:22 UTC, MaksymTerekhovskyy commented on src/Client/View/LoginPage/LoginPage.cpp
> +	loginInDTO.login	= ui->loginLineEdit->text().toStdString();
fixed in the last commit

2022-01-16 18:22 UTC, MaksymTerekhovskyy commented on src/Client/View/MainWindow.h
> +	static int PageToInt(UIPages page);
fixed in the last commit

2022-01-16 18:24 UTC, MaksymTerekhovskyy commented on src/Client/Models/LoginModel.cpp
> +    json.insert("password", QString(encrypted_password));
fixed in the last commit

2022-01-17 09:08 UTC, AndriyFedorenko approved these changes

2022-01-17 18:09 UTC, yaroslav-kernitskyi commented on src/Client/Models/LoginModel.cpp
> +    encrypted_password = QCryptographicHash::hash(encrypted_password, QCryptographicHash::Sha1);
Storing unencrypted password in variable with name `encrypted_password` is a bit confusing.
Do you really need to store it, if you only use it once?  I suggest something like:
```
QByteArray encrypted_password = QCryptographicHash::hash(
		QByteArray::fromStdString(dto.password),
		QCryptographicHash::Sha1);
```
or
```
QByteArray unencrypted_password = QByteArray::fromStdString(dto.password);
QByteArray encrypted_password = QCryptographicHash::hash(unencrypted_password, QCryptographicHash::Sha1);
```
Also what you are doing is not really encryption, but hashing, so consider renaming variables accordingly.

2022-01-17 18:18 UTC, yaroslav-kernitskyi commented on src/Client/Controller/Controller.cpp
> +					, tr("Login failed!")
`tr` is used for translation. Will we implement it?

2022-01-17 18:35 UTC, yaroslav-kernitskyi commented on src/Client/View/LoginPage/LoginPage.h
>      void on_loginSubmitButton_clicked();
I don't like that `on_loginSubmitButton_clicked` slot is basically method, but does not follow code convention for methods. We should discuss signal/slot naming with team. Also it's better to connect button signal to this slot explicitly in constructor.

2022-01-17 19:53 UTC, sorbeee approved these changes

2022-01-17 21:20 UTC, MaksymTerekhovskyy commented on src/Client/Controller/Controller.cpp
> +					, tr("Login failed!")
No, I replaced tr in the last commit

2022-01-17 21:21 UTC, MaksymTerekhovskyy commented on src/Client/View/LoginPage/LoginPage.h
>      void on_loginSubmitButton_clicked();
fixed in the last commit

I just named this slot as a regular method

2022-01-17 21:21 UTC, MaksymTerekhovskyy commented on src/Client/Models/LoginModel.cpp
> +    encrypted_password = QCryptographicHash::hash(encrypted_password, QCryptographicHash::Sha1);
Yes, we don`t need to story this password in a variable if we use it only once, but if I put QByteArray::fromStdString(dto.password) into insert method the code will look awkward and will be difficult to read so I decided not to delete this variable

In the last commit I renamed it

2022-01-18 15:28 UTC, Denys-Bykov-0 requested changes

2022-01-18 15:28 UTC, Denys-Bykov-0 commented on src/Client/View/LoginPage/LoginPage.h
> +    Ui::LoginPage *ui;
Rename this variable to the m_ui, I did the same to HomePage.

2022-01-18 15:39 UTC, yaroslav-kernitskyi approved these changes
I don't see any apparent issues

2022-01-18 15:47 UTC, MaksymTerekhovskyy commented on src/Client/View/LoginPage/LoginPage.h
> +    Ui::LoginPage *ui;
renamed in the last commit

2022-01-18 16:14 UTC, Denys-Bykov-0 approved these changes

2022-01-18 16:21 UTC, merged