Serhii lakhman
iodream/Spend-Note pull request #15
Opened 2022-01-17 21:58 UTC by sorbeee

2022-01-18 06:50 UTC, VasylDobrovolskyi commented on src/Server/libdal/Facade/idbfacade.h
> +	virtual void RemoveUser(IdType id) = 0;
Something wrong with code formatting.

2022-01-18 06:51 UTC, VasylDobrovolskyi commented on src/Server/libdal/Facade/idbfacade.h
> +    virtual std::optional<Income> GetIncomeById(const IdType& id) = 0;
Something wrong with code formatting.

2022-01-18 06:51 UTC, VasylDobrovolskyi commented on src/Server/libdal/Facade/dbfacade.h
> +    std::optional<Income> GetIncomeById(const IdType& id) override;
Something wrong with code formatting.

2022-01-18 06:51 UTC, VasylDobrovolskyi commented on src/Server/libdal/Facade/dbfacade.h
> +    ListRepository m_lists;
Something wrong with code formatting.

2022-01-18 06:52 UTC, VasylDobrovolskyi commented on src/Server/libdal/Repositories/ListRepository/ListRepository.cpp
> +
Something wrong with code formatting.

2022-01-18 07:00 UTC, VasylDobrovolskyi commented on src/Server/libdal/Facade/dbfacade.cpp
> +    m_incomes.Add(income);
Something wrong with code formatting. There is different length before Remove method and Add method.

2022-01-18 07:04 UTC, VasylDobrovolskyi commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.h
> +    void Remuve(const idType& id);
Maybe you meant "remove".

2022-01-18 10:11 UTC, Denys-Bykov-0 requested changes

2022-01-18 10:11 UTC, Denys-Bykov-0 commented on src/Server/libdal/Facade/dbfacade.cpp
> +void DbFacade::AddList(const List &list_)
Why are you placing "_" at the end of variable name, please remove it wherever possible.

2022-01-18 10:11 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +    catch(const pqxx::pqxx_exception& e)
Consider passing error message from pqxx_exception to the DatabaseFailure.

2022-01-18 10:11 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/ListRepository/ListRepository.h
> +    ListRepository(pqxx::connection& database_connection);
Word database in the name of variable database_connection may be redundant. Remove it, or shorten, and also synchronize with other repositories.

2022-01-18 14:45 UTC, AndriyFedorenko commented on src/Server/libdal/Facade/dbfacade.cpp
> +void DbFacade::AddIncome(const Income &income)
you write `type &name;` some time `type& mane;` please use the same style everywhere

2022-01-18 14:45 UTC, AndriyFedorenko commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +    w.exec0("INSERT INTO " + TABLE_NAME + " (" + USER_ID + ", " + INCOME_NAME + ", " + AMOUNT + ", "
Why don’t you handle exceptions?

2022-01-18 14:45 UTC, AndriyFedorenko commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +    pqxx::work w{m_databaseConnection};
Work can also throw exception if connection is invalid for instance.

2022-01-18 14:45 UTC, AndriyFedorenko commented on src/Server/libdal/Repositories/ListRepository/ListRepository.cpp
> +ListRepository::ListRepository(pqxx::connection& database_connection) : m_database_connection(database_connection)
Please add const

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/DTOs/Income.h
> +    std::string name;
Indentation issue.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Facade/dbfacade.cpp
> +														   m_incomes(m_connection), m_lists(m_connection),
Indentation issue. Please reformat initializer list to look like this:

ListSubPage::ListSubPage(const QString& name, int id, QWidget *parent)
	: QWidget(parent)
	, m_ui(new Ui::ListSubPage)
	, m_name(name)
	, m_id(id)
{

}

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Facade/dbfacade.cpp
> +void DbFacade::UpdateUser(const User &user)
Write Type& var_name everywhere.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/DTOs/IncomeCategory.h
> +    std::string name;
Indentation issue.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/IncomeCategoryRepository/IncomeCategoryRepository.cpp
> +
So many blank lines at the end of the file, for what?

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +		pqxx::row income = w.exec1("SELECT * FROM " + TABLE_NAME + " WHERE " + ID_FIELD + " = "  + w.quote(income_id) + ";");
Indentation.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +			return Income{income[ID_FIELD].as<IdType>(), income[USER_ID].as<IdType>(),
Really bad indentation issue.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/IncomeRepository/IncomeRepository.cpp
> +
Too many blank lines.

2022-01-20 11:22 UTC, Denys-Bykov-0 commented on src/Server/libdal/Repositories/ListRepository/ListRepository.cpp
> +			return List{list[ID_FIELD].as<IdType>(), list[USER_ID].as<IdType>(),
Another indentation issue.

2022-01-20 11:35 UTC, yaroslav-kernitskyi commented
dbfacade.cpp was not deleted

2022-01-20 11:51 UTC, yaroslav-kernitskyi commented on src/Server/libdal/Facade/dbfacade.cpp
> +														   m_incomes(m_connection), m_lists(m_connection),
@Denys-Bykov-0, consider using ctrl+e or <> button on tool panel to format code. It looks better and it is easier to copy.
```
ListSubPage::ListSubPage(const QString& name, int id, QWidget *parent)
	: QWidget(parent)
	, m_ui(new Ui::ListSubPage)
	, m_name(name)
	, m_id(id)
{

}
```

2022-01-20 17:45 UTC, Denys-Bykov-0 approved these changes

2022-01-20 18:05 UTC, VasylDobrovolskyi approved these changes

2022-01-20 18:09 UTC, yaroslav-kernitskyi approved these changes

2022-01-20 18:09 UTC, yaroslav-kernitskyi commented on src/Server/libdal/Exceptions/DatabaseFailure.h
> +#include "pqxx/pqxx"
Do you really need it here?

2022-01-20 19:37 UTC, merged