Close CPPL - 249 & CPPL - 246
iodream/Spend-Note pull request #151
Opened 2022-04-03 21:43 UTC by sorbeee

2022-04-04 08:38 UTC, iodream requested changes

2022-04-04 08:38 UTC, iodream commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +			QString label = GetIncomeCategoryById(el.category_id, category) + " " +QString::number(el.percentage) + "%";
```suggestion
			QString label = GetIncomeCategoryById(el.category_id, category) + " " + QString::number(el.percentage) + "%";
```

2022-04-04 08:38 UTC, iodream commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +			QString label = GetProductCategoryById(el.category_id, category) + " " +QString::number(el.percentage) + "%";
```suggestion
			QString label = GetProductCategoryById(el.category_id, category) + " " + QString::number(el.percentage) + "%";
```

2022-04-04 08:38 UTC, iodream commented on src/Client/View/MainPage/Statistic/StatisticSubPage.h
> +	QString GetProductCategoryById(IdType id, std::vector<ProductCategory> category);
consider using const references for the parameters in these functions

2022-04-04 18:47 UTC, VasylDobrovolskyi approved these changes

2022-04-05 16:36 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +		ShowEmptyMessang();
Typo `Messang -> Message`

2022-04-05 16:37 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +			QString lable = GetProductCategoryById(el.category_id, category) + " " + QString::number(el.amount) + "$";
Typo `lable -> label`

2022-04-05 16:44 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +		ChartChanged(current_index);
`if` and `else` branches look very similar. Create function to avoid duplication.

2022-04-05 16:45 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +		ChartChanged(current_index);
Same as previous function

2022-04-05 17:00 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.cpp
> +void StatisticSubPage::ShowEmptyMessang()
Don't forget to rename. Also function looks repetitive and hardcoded (probably problems with architecture).

2022-04-05 17:01 UTC, yaroslav-kernitskyi commented on src/Client/View/MainPage/Statistic/StatisticSubPage.ui
> +           <normaloff>../../../Icons/baseline_arrow_forward_ios_black_24dp.png</normaloff>../../../Icons/baseline_arrow_forward_ios_black_24dp.png</iconset>
Why so many `../../../`?

2022-04-05 17:02 UTC, yaroslav-kernitskyi approved these changes

2022-04-05 19:09 UTC, iodream approved these changes

2022-04-05 19:12 UTC, merged