Closes CPPL-252
iodream/Spend-Note pull request #154
Opened 2022-04-04 08:08 UTC by yaroslav-kernitskyi

Added period to statistics

2022-04-04 18:49 UTC, VasylDobrovolskyi approved these changes

2022-04-04 20:37 UTC, sorbeee requested changes

2022-04-04 20:37 UTC, sorbeee commented on src/Server/libdal/Facade/IDbFacade.h
> +	virtual std::vector<IncomePerCategory> IncomesPerCategory(IdType user_id, Period period);
You forgot = 0 in the end

2022-04-05 10:37 UTC, sorbeee approved these changes

2022-04-05 14:35 UTC, merged