Closes CPPL-271
iodream/Spend-Note pull request #177
Opened 2022-05-02 13:31 UTC by MaksymTerekhovskyy

- added server support for the change of email

2022-05-02 14:17 UTC, sorbeee requested changes

2022-05-02 14:17 UTC, sorbeee commented on src/Server/Handlers/User/ChangeEmailHandler.cpp
> +    if (!verification.has_value()) {
if ( ... )
{
//code
}

2022-05-02 14:17 UTC, sorbeee commented on src/Server/Handlers/User/ChangeEmailHandler.h
> +        struct DTO
I think that parsers need to be moved from handlers

2022-05-02 14:17 UTC, sorbeee commented on src/Server/libdal/Repositories/UserRepository/UserRepository.cpp
> +        auto result = w.exec("SELECT " + user::ID + " FROM  " + user::TABLE_NAME + " WHERE " + user::ID + " = " + w.quote(GetById(user_id)));
Something wrong with code formatting

2022-05-02 14:17 UTC, sorbeee commented on src/Server/libdal/Repositories/UserRepository/UserRepository.cpp
> +                user::EMAIL + " = " + w.quote(email) +
Something wrong with code formatting too

2022-05-02 21:32 UTC, sorbeee approved these changes

2022-05-03 07:50 UTC, sorbeee commented on src/Server/libdal/Repositories/UserRepository/UserRepository.cpp
>  		auto result = w.exec("SELECT " + user::ID + " FROM  " + user::TABLE_NAME + " WHERE " + user::ID + " = " + w.quote(user_id));
Please write like this:

pqxx::result user_ids = work.exec(
  "SELECT " + user::ID +
  " FROM " + user::TABLE_NAME +
  " WHERE " + user::ID + " = " + work.quote(user_id) + ";");

2022-05-03 11:01 UTC, yaroslav-kernitskyi commented on src/Server/libdal/Repositories/UserRepository/UserRepository.cpp
> +			user::EMAIL + " = " + w.quote(email) +
I think in this case there is not need to move this part to the next line
`" SET " + user::EMAIL + " = " + w.quote(email) +`

2022-05-03 11:02 UTC, yaroslav-kernitskyi commented on src/Client/Models/User/ChangeEmailModel.cpp
> +	request.uri = m_hostname + "/change-email";
Why not `/email` and PUT method?

2022-05-03 11:07 UTC, yaroslav-kernitskyi approved these changes

2022-05-03 20:16 UTC, merged