Closes CPPL-132
iodream/Spend-Note pull request #24
Opened 2022-01-21 17:08 UTC by yaroslav-kernitskyi

2022-01-21 18:23 UTC, Denys-Bykov-0 commented on src/Server/Handlers/GetIncomesHandler/GetIncomesHandler.cpp
> +		income_json["id"] = income.income_id;
Currently we are using string for ids in json, so replace all such occurrences with std::to_string(id_name).c_str().

2022-01-22 19:32 UTC, Denys-Bykov-0 commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	JSONFormatter::Income MapIncome(Income income);
const Income&

2022-01-22 19:32 UTC, Denys-Bykov-0 commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	JSONFormatter::Incomes Map(std::vector<Income> incomes);
Wouldn't it be better to use std::vector<Income>&&?

2022-01-23 07:45 UTC, VasylDobrovolskyi commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	class JSONParser
Maybe it would be better to delete this class, because you don't use it

2022-01-23 19:51 UTC, yaroslav-kernitskyi commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	JSONFormatter::Income MapIncome(Income income);
Fixed

2022-01-23 19:54 UTC, yaroslav-kernitskyi commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	JSONFormatter::Incomes Map(std::vector<Income> incomes);
Isn't const std::vector& enough? I create vector of different type inside function.

2022-01-23 20:13 UTC, sorbeee approved these changes

2022-01-23 20:28 UTC, yaroslav-kernitskyi commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +	class JSONParser
Fixed

2022-01-23 21:10 UTC, AndriyFedorenko commented on src/Server/HandlerFactory.cpp
> +	if (uri == std::string("/income/get"))
Here is recommendation about naming in REST
 https://restfulapi.net/resource-naming/

2022-01-23 21:13 UTC, AndriyFedorenko commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +		struct DTO
I don't understand why you need this structure

2022-01-23 21:59 UTC, yaroslav-kernitskyi commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +		struct DTO
It gets formatted to json
```
{
	"incomes" : [ ... ]
}
```
Some guys on stackoverflow say that returning json object is best practice. And Format(std::vector) returning something other than json array feels awkward

2022-01-23 22:00 UTC, yaroslav-kernitskyi commented on src/Server/HandlerFactory.cpp
> +	if (uri == std::string("/income/get"))
Can we do implement such naming without completely rewriting our handler factory and handlers?

2022-01-24 09:48 UTC, Denys-Bykov-0 commented on src/Server/Handlers/Income/GetIncomesHandler.h
> +		struct DTO
I'm think that he is about DTO structure with only one field.

2022-01-24 18:24 UTC, Denys-Bykov-0 approved these changes

2022-01-24 19:31 UTC, VasylDobrovolskyi approved these changes

2022-01-24 22:03 UTC, Denys-Bykov-0 requested changes

2022-01-24 22:03 UTC, Denys-Bykov-0 commented on src/Server/Handlers/Income/GetIncomesHandler.cpp
> +		catch (const DatabaseFailure& e)
Please do not do this at this level. DatabaseFailure is meant for something more important than just DML failure, and Handler could not recover from this situation. Just remove it and leave it to the higher level methods. If you want to you can catch SQLFailure instead.

2022-01-25 11:04 UTC, Denys-Bykov-0 approved these changes

2022-01-25 18:54 UTC, merged