Closes CPPL-176
iodream/Spend-Note pull request #51
Opened 2022-02-01 12:02 UTC by VasylDobrovolskyi

2022-02-01 16:57 UTC, Denys-Bykov-0 requested changes

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/Utils.cpp
> +	SafeWritePrice(json, "price", product.price);
Why SafeWrite, it can throw an exception? If no rename to WtireMoney(It can be used not only with price)

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/Utils.cpp
> +ProductCategory ParseProductCategory(const QJsonObject& json)
I think it would be better to create separate classes for each parser and formatter as you did for data structures. That might be a little redundant, but easier to manage in future.

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Net/Parsing.cpp
> +		double* ptr = &id;
You don't really need this ptr variable

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Net/Parsing.cpp
> +	return SafeReadId(json, label.c_str(), dest);
Wrong function call

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Net/Parsing.cpp
> +	return SafeReadId(json, label.c_str(), dest);
Wrong function call

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Net/Parsing.cpp
> +	return SafeReadId(json, label.c_str(), dest);
Wrong function call

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Server/Handlers/ParsersAndFormatters/ProductParse.h
> +	QJsonObject json_for_category;
Just category or category_json

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Server/Handlers/ParsersAndFormatters/ProductParse.h
> +Product ProductParse(QJsonObject& json)
I recommend rename it to the ParseProduct, it feels more natural and consistent with other code

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Server/Handlers/ParsersAndFormatters/ProductIdParse.h
> +ProductId ProductIdParse(QJsonObject& json)
The same as with ProductParse

2022-02-01 16:57 UTC, Denys-Bykov-0 commented on src/Server/Handlers/ParsersAndFormatters/ProductIdParse.h
> +ProductId ProductIdParse(QJsonObject& json)
Why are you writing implementation in the header, and also why that is not a separate ProductParser class? The same thing with other code.

2022-02-02 10:20 UTC, Denys-Bykov-0 reviewed
It should be better to turn all your entities into class templates, so you won't be forced to create the same structures on client and server side, which differ only by string type. To use them in convenient way you also can define appropriate aliases on client and server, for example:
using Product = Product<std::string> for the server

2022-02-02 10:20 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/ProductCategoryJSONFormatter.h
> +	QJsonDocument FormatProductCategory(ProductCategory& category);
Just Format, the rest can be learned from the context.

2022-02-02 10:20 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/ProductCategoryJSONFormatter.h
> +	QJsonDocument FormatProductCategory(ProductCategory& category);
const ProductCategory&

2022-02-02 10:20 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/ProductCategoryJSONParser.h
> +	ProductCategory ParseProductCategory(const QJsonObject& json);
Just Parse

2022-02-02 15:34 UTC, Denys-Bykov-0 approved these changes

2022-02-02 15:46 UTC, iodream approved these changes

2022-02-02 16:18 UTC, Denys-Bykov-0 commented on src/Client/Models/Product/Utils.cpp
> +	product.priority = tmp_number;
Should be replaced with SafeReadBigInt

2022-02-02 17:38 UTC, Denys-Bykov-0 approved these changes

2022-02-02 17:41 UTC, merged