Closes CPPL-141
iodream/Spend-Note pull request #53
Opened 2022-02-01 23:44 UTC by iodream

Implemented Scoped Logger and used it for all major methods

2022-02-02 10:43 UTC, Denys-Bykov-0 requested changes

2022-02-02 10:43 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.h
> +	std::string m_fileName;
Why camel case in the name of variables?

2022-02-02 10:43 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.h
> +	static std::ofstream m_logger;
Why name of stream is logger? Please rename it to something like a stream or os

2022-02-02 10:43 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.cpp
> +	m_logger << "\n" << fileName <<": line "<<lineNr <<": "<< funcName
Not thread safe

2022-02-02 14:50 UTC, iodream commented on src/Logger/ScopedLogger.cpp
> +	m_logger.close();
i thought i had a bug here but as it turns out we are fine

2022-02-02 14:50 UTC, iodream commented on src/Logger/ScopedLogger.cpp
> +	m_logger << "\n" << fileName <<": line "<<lineNr <<": "<< funcName
added thread safety

2022-02-02 16:15 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.cpp
> +	std::remove(m_logfilename.c_str()); // remove previous file
We definitely don't want to delete logs from our code

2022-02-02 16:15 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.h
> +	static QMutex m_logmutex;
std::mutex

2022-02-02 16:24 UTC, iodream commented on src/Logger/ScopedLogger.cpp
> +	std::remove(m_logfilename.c_str()); // remove previous file
Init is mostly meant to be called at the beginning of program execution to set a custom file name if we want. So it would delete only an empty file. I could add a check to see if the file is empty.

2022-02-02 16:28 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.cpp
> +	std::remove(m_logfilename.c_str()); // remove previous file
In this case remove this file closing and removing at all

2022-02-02 16:44 UTC, iodream commented on src/Logger/ScopedLogger.cpp
> +	std::remove(m_logfilename.c_str()); // remove previous file
removed file removing but the file closing is necessary because the default log file already exists by the time Init is called. if i dont close the stream before opening the new file then nothing will get logged at all.

2022-02-02 17:14 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.cpp
> +	m_stream.close();	// close previous file if we are changing logs mid-app execution
Remove this

2022-02-02 17:14 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.cpp
> +std::string ScopedLogger::m_logfilename("ScopedLogger.log");
Do not initialize those variables, you have Init for that

2022-02-02 17:14 UTC, Denys-Bykov-0 commented on src/Logger/ScopedLogger.h
> +	std::string m_funcname;
Use a proper snake case, for example rename it to m_func_name. Same with other names

2022-02-02 18:35 UTC, Denys-Bykov-0 commented on src/Logger/Logger.cpp
> +QMutex Logger::m_log_mutex;
Again QMutex

2022-02-02 18:38 UTC, iodream commented on src/Logger/Logger.cpp
> +QMutex Logger::m_log_mutex;
since this is the logger that uses qDebug, i thought QMutex would be more appropriate. Should i switch to std::mutex?

2022-02-02 18:42 UTC, Denys-Bykov-0 commented on src/Logger/Logger.cpp
> +QMutex Logger::m_log_mutex;
I think that QMutex exists for historical reasons, like a QThread. In our project we mainly use std::thread library, so yes, that will be better.

2022-02-03 09:02 UTC, Denys-Bykov-0 approved these changes

2022-02-03 09:44 UTC, MaksymTerekhovskyy approved these changes

2022-02-03 20:38 UTC, merged